<?
/*
 * countries.php:
 * Data on countries and (in some cases) named divisions within them.
 * 
 * Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
 * Email: francis@mysociety.org. WWW: http://www.mysociety.org
 *
 * $Id: countries.php,v 1.13 2006-07-03 09:51:25 francis Exp $
 * 
 */

/* $countries_name_to_code
 * ISO 3166-1 alpha-2 country names and two letter codes, taken from
 * http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2. */
$countries_code_to_name = array(
    "AF" => _("Afghanistan"),
    "AX" => _("Åland Islands"),
    "AL" => _("Albania"),
    "DZ" => _("Algeria"),
    "AS" => _("American Samoa"),
    "AD" => _("Andorra"),
    "AO" => _("Angola"),
    "AI" => _("Anguilla"),
    "AQ" => _("Antarctica"),
    "AG" => _("Antigua and Barbuda"),
    "AR" => _("Argentina"),
    "AM" => _("Armenia"),
    "AW" => _("Aruba"),
    "AU" => _("Australia"),
    "AT" => _("Austria"),
    "AZ" => _("Azerbaijan"),
    "BS" => _("Bahamas"),
    "BH" => _("Bahrain"),
    "BD" => _("Bangladesh"),
    "BB" => _("Barbados"),
    "BY" => _("Belarus"),
    "BE" => _("Belgium"),
    "BZ" => _("Belize"),
    "BJ" => _("Benin"),
    "BM" => _("Bermuda"),
    "BT" => _("Bhutan"),
    "BO" => _("Bolivia"),
    "BA" => _("Bosnia and Herzegovina"),
    "BW" => _("Botswana"),
    "BV" => _("Bouvet Island"),
    "BR" => _("Brazil"),
    "IO" => _("British Indian Ocean Territory"),
    "VG" => _("British Virgin Islands"),
    "BN" => _("Brunei"),
    "BG" => _("Bulgaria"),
    "BF" => _("Burkina Faso"),
    "BI" => _("Burundi"),
    "KH" => _("Cambodia"),
    "CM" => _("Cameroon"),
    "CA" => _("Canada"),
    "CV" => _("Cape Verde"),
    "KY" => _("Cayman Islands"),
    "CF" => _("Central African Republic"),
    "TD" => _("Chad"),
    "CL" => _("Chile"),
    "CN" => _("China"),
    "CX" => _("Christmas Island"),
    "CC" => _("Cocos (Keeling) Islands"),
    "CO" => _("Colombia"),
    "KM" => _("Comoros"),
    "CG" => _("Congo"),
    "CK" => _("Cook Islands"),
    "CR" => _("Costa Rica"),
    "CI" => _("Côte d'Ivoire"),
    "HR" => _("Croatia"),
    "CU" => _("Cuba"),
    "CY" => _("Cyprus"),
    "CZ" => _("Czech Republic"),
    "CD" => _("Democratic Republic of the Congo"),
    "DK" => _("Denmark"),
    "DJ" => _("Djibouti"),
    "DM" => _("Dominica"),
    "DO" => _("Dominican Republic"),
    "TL" => _("East Timor"),
    "EC" => _("Ecuador"),
    "EG" => _("Egypt"),
    "SV" => _("El Salvador"),
    "GQ" => _("Equatorial Guinea"),
    "ER" => _("Eritrea"),
    "EE" => _("Estonia"),
    "ET" => _("Ethiopia"),
    "FK" => _("Falkland Islands"),
    "FO" => _("Faroe Islands"),
    "FM" => _("Federated States of Micronesia"),
    "FJ" => _("Fiji"),
    "FI" => _("Finland"),
    "FR" => _("France"),
    "GF" => _("French Guiana"),
    "PF" => _("French Polynesia"),
    "TF" => _("French Southern Territories"),
    "GA" => _("Gabon"),
    "GM" => _("Gambia"),
    "GE" => _("Georgia"),
    "DE" => _("Germany"),
    "GH" => _("Ghana"),
    "GI" => _("Gibraltar"),
    "GR" => _("Greece"),
    "GL" => _("Greenland"),
    "GD" => _("Grenada"),
    "GP" => _("Guadeloupe"),
    "GU" => _("Guam"),
    "GT" => _("Guatemala"),
    "GW" => _("Guinea-Bissau"),
    "GN" => _("Guinea"),
    "GY" => _("Guyana"),
    "HT" => _("Haiti"),
    "HM" => _("Heard Island and McDonald Islands"),
    "HN" => _("Honduras"),
    "HK" => _("Hong Kong"),
    "HU" => _("Hungary"),
    "IS" => _("Iceland"),
    "IN" => _("India"),
    "ID" => _("Indonesia"),
    "IR" => _("Iran"),
    "IQ" => _("Iraq"),
    "IE" => _("Ireland"),
    "IL" => _("Israel"),
    "IT" => _("Italy"),
    "JM" => _("Jamaica"),
    "JP" => _("Japan"),
    "JO" => _("Jordan"),
    "KZ" => _("Kazakhstan"),
    "KE" => _("Kenya"),
    "KI" => _("Kiribati"),
    "KW" => _("Kuwait"),
    "KG" => _("Kyrgyzstan"),
    "LA" => _("Laos"),
    "LV" => _("Latvia"),
    "LB" => _("Lebanon"),
    "LS" => _("Lesotho"),
    "LR" => _("Liberia"),
    "LY" => _("Libya"),
    "LI" => _("Liechtenstein"),
    "LT" => _("Lithuania"),
    "LU" => _("Luxembourg"),
    "MO" => _("Macao"),
    "MG" => _("Madagascar"),
    "MW" => _("Malawi"),
    "MY" => _("Malaysia"),
    "MV" => _("Maldives"),
    "ML" => _("Mali"),
    "MT" => _("Malta"),
    "MH" => _("Marshall Islands"),
    "MQ" => _("Martinique"),
    "MR" => _("Mauritania"),
    "MU" => _("Mauritius"),
    "YT" => _("Mayotte"),
    "MX" => _("Mexico"),
    "MD" => _("Moldova"),
    "MC" => _("Monaco"),
    "MN" => _("Mongolia"),
    "MS" => _("Montserrat"),
    "MA" => _("Morocco"),
    "MZ" => _("Mozambique"),
    "MM" => _("Myanmar"),
    "NA" => _("Namibia"),
    "NR" => _("Nauru"),
    "NP" => _("Nepal"),
    "NL" => _("Netherlands"),
    "AN" => _("Netherlands Antilles"),
    "NC" => _("New Caledonia"),
    "NZ" => _("New Zealand"),
    "NI" => _("Nicaragua"),
    "NG" => _("Nigeria"),
    "NE" => _("Niger"),
    "NU" => _("Niue"),
    "NF" => _("Norfolk Island"),
    "KP" => _("North Korea"),
    "MP" => _("Northern Mariana Islands"),
    "NO" => _("Norway"),
    "OM" => _("Oman"),
    "PK" => _("Pakistan"),
    "PW" => _("Palau"),
    "PS" => _("Palestinian Territories"),
    "PA" => _("Panama"),
    "PG" => _("Papua New Guinea"),
    "PY" => _("Paraguay"),
    "PE" => _("Peru"),
    "PH" => _("Philippines"),
    "PN" => _("Pitcairn Islands"),
    "PL" => _("Poland"),
    "PT" => _("Portugal"),
    "PR" => _("Puerto Rico"),
    "QA" => _("Qatar"),
    "RE" => _("Réunion"),
    "MK" => _("Republic of Macedonia"),
    "RO" => _("Romania"),
    "RU" => _("Russia"),
    "RW" => _("Rwanda"),
    "SH" => _("Saint Helena"),
    "KN" => _("Saint Kitts and Nevis"),
    "LC" => _("Saint Lucia"),
    "PM" => _("Saint-Pierre and Miquelon"),
    "VC" => _("Saint Vincent and the Grenadines"),
    "WS" => _("Samoa"),
    "SM" => _("San Marino"),
    "ST" => _("São Tomé and Príncipe"),
    "SA" => _("Saudi Arabia"),
    "SN" => _("Senegal"),
    "CS" => _("Serbia and Montenegro"),
    "SC" => _("Seychelles"),
    "SL" => _("Sierra Leone"),
    "SG" => _("Singapore"),
    "SK" => _("Slovakia"),
    "SI" => _("Slovenia"),
    "SB" => _("Solomon Islands"),
    "SO" => _("Somalia"),
    "ZA" => _("South Africa"),
    "GS" => _("South Georgia and the South Sandwich Islands"),
    "KR" => _("South Korea"),
    "ES" => _("Spain"),
    "LK" => _("Sri Lanka"),
    "SD" => _("Sudan"),
    "SR" => _("Suriname"),
    "SJ" => _("Svalbard"),
    "SZ" => _("Swaziland"),
    "SE" => _("Sweden"),
    "CH" => _("Switzerland"),
    "SY" => _("Syria"),
    "TW" => _("Taiwan"),
    "TJ" => _("Tajikistan"),
    "TZ" => _("Tanzania"),
    "TH" => _("Thailand"),
    "TG" => _("Togo"),
    "TK" => _("Tokelau"),
    "TO" => _("Tonga"),
    "TT" => _("Trinidad and Tobago"),
    "TN" => _("Tunisia"),
    "TR" => _("Turkey"),
    "TM" => _("Turkmenistan"),
    "TC" => _("Turks and Caicos Islands"),
    "TV" => _("Tuvalu"),
    "UG" => _("Uganda"),
    "UA" => _("Ukraine"),
    "AE" => _("United Arab Emirates"),
    "GB" => _("United Kingdom"),
    "US" => _("United States"),
    "UM" => _("United States Minor Outlying Islands"),
    "UY" => _("Uruguay"),
    "VI" => _("U.S. Virgin Islands"),
    "UZ" => _("Uzbekistan"),
    "VU" => _("Vanuatu"),
    "VA" => _("Vatican City"),
    "VE" => _("Venezuela"),
    "VN" => _("Vietnam"),
    "WF" => _("Wallis and Futuna"),
    "EH" => _("Western Sahara"),
    "YE" => _("Yemen"),
    "ZM" => _("Zambia"),
    "ZW" => _("Zimbabwe"),
);

/* $countries_code_to_name
 * Map from ISO 3166 code to country name. */
$countries_name_to_code = array();
foreach ($countries_code_to_name as $countries_code => $countries_name) {
    if (array_key_exists($countries_name, $countries_name_to_code)) {
        die("Name $countries_name exists twice in countries_code_to_name");
    }
    $countries_name_to_code[$countries_name] = $countries_code;
}

/* $countries_statecode_to_name
 * Top-level administrative areas within countries and identifying codes for
 * them. */
$countries_statecode_to_name = array(
    'US' => array(
        'AK' => 'Alaska',
        'AL' => 'Alabama',
        'AR' => 'Arkansas',
        'AZ' => 'Arizona',
        'CA' => 'California',
        'CO' => 'Colorado',
        'CT' => 'Connecticut',
        'DE' => 'Delaware',
        'FL' => 'Florida',
        'GA' => 'Georgia',
        'HI' => 'Hawaii',
        'IA' => 'Iowa',
        'ID' => 'Idaho',
        'IL' => 'Illinois',
        'IN' => 'Indiana',
        'KS' => 'Kansas',
        'KY' => 'Kentucky',
        'LA' => 'Louisiana',
        'MA' => 'Massachusetts',
        'MD' => 'Maryland',
        'ME' => 'Maine',
        'MI' => 'Michigan',
        'MN' => 'Minnesota',
        'MO' => 'Missouri',
        'MS' => 'Mississippi',
        'MT' => 'Montana',
        'NC' => 'North Carolina',
        'ND' => 'North Dakota',
        'NE' => 'Nebraska',
        'NH' => 'New Hampshire',
        'NJ' => 'New Jersey',
        'NM' => 'New Mexico',
        'NV' => 'Nevada',
        'NY' => 'New York',
        'OH' => 'Ohio',
        'OK' => 'Oklahoma',
        'OR' => 'Oregon',
        'PA' => 'Pennsylvania',
        'RI' => 'Rhode Island',
        'SC' => 'South Carolina',
        'SD' => 'South Dakota',
        'TN' => 'Tennessee',
        'TX' => 'Texas',
        'UT' => 'Utah',
        'VT' => 'Vermont',
        'VA' => 'Virginia',
        'WA' => 'Washington',
        'WI' => 'Wisconsin',
        'WV' => 'West Virginia',
        'WY' => 'Wyoming'
    )
);

/* countries_sort CODE_A CODE_B
 * Takes two country codes, such as GB and CN. Returns -1, 0, or 1
 * according to how their full names are alphabetically sorted.
 * For use with PHP sort functions.
 */
function countries_sort($a, $b) {
    global $countries_code_to_name;
    return strcoll($countries_code_to_name[$a], $countries_code_to_name[$b]);
}


?>
