<?php
/* 
 * THIS FILE WAS AUTOMATICALLY GENERATED BY ./rabxtophp.pl, DO NOT EDIT DIRECTLY
 * 
 * gaze.php:
 * Implementation of Gaze
 *
 * Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
 * WWW: http://www.mysociety.org
 *
 * $Id: gaze.php,v 1.2 2005-07-22 13:57:39 francis Exp $
 *
 */

require_once('rabx.php');

/* gaze_get_error R
 * Return FALSE if R indicates success, or an error string otherwise. */
function gaze_get_error($e) {
    if (!rabx_is_error($e))
        return FALSE;
    else
        return $e->text;
}

/* gaze_check_error R
 * If R indicates failure, displays error message and stops procesing. */
function gaze_check_error($data) {
    if ($error_message = gaze_get_error($data))
        err($error_message);
}

$gaze_client = new RABX_Client(OPTION_GAZE_URL);


/* gaze_find_places COUNTRY QUERY [MAXRESULTS]

  Search for places in COUNTRY (ISO code) which match the given search
  QUERY. Returns a reference to a list of [NAME, QUALIFICATION, QUALIFIER,
  LATITUDE, LONGITUDE]. When NAME is unique, QUALIFICATION and QUALIFIER
  will be undef; otherwise, QUALIFICATION will either be 'in' and QUALIFIER
  the name of an enclosing administrative area (for instance, a state or
  county), or 'near' and the names of nearby places, respectively. LATITUDE
  and LONGITUDE are in decimal degrees, north- and east-positive, in WGS84.
  Earlier entries in the returned list are better matches to the query. At
  most MAXRESULTS (default, 10) results are returned. On error, throws an
  exception. */
function gaze_find_places($country, $query, $maxresults = null) {
    global $gaze_client;
    $params = func_get_args();
    $result = $gaze_client->call('Gaze.find_places', $params);
    return $result;
}

/* gaze_get_country_from_ip ADDRESS

  Return the country code for the given IP address, or undef if none could
  be found. */
function gaze_get_country_from_ip($address) {
    global $gaze_client;
    $params = func_get_args();
    $result = $gaze_client->call('Gaze.get_country_from_ip', $params);
    return $result;
}


?>
