name: Ruby Tests and Specs

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
        working-directory: ./rblib

    - name: Run tests
      working-directory: ./rblib
      run: bundle exec rake test:commonlib

    - name: Run specs
      working-directory: ./rblib
      run: bundle exec rake spec:commonlib
